#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

# NO_PERINCI_CMDLINE_SCRIPT
# FRAGMENT id=shcompgen-hint completer=1 for=cpanm

use 5.010001;
use strict;
use warnings;
use App::ShellCompleter::cpanm;

App::ShellCompleter::cpanm::run_completer();

# ABSTRACT: Shell completer for cpanm
# PODNAME:

=head1 SYNOPSIS

To install, install this module and then in your bash (and/or bash startup
file):

 complete -C _cpanm cpanm

or, you can use L<shcompgen> to do that for you automatically.

Now L<cpanm> has bash completion:

 % cpanm --s<tab>
 % cpanm -n Bencher::<tab>
 % cpanm --uninstall "Text::A<tab>


=head1 DESCRIPTION


=head1 ENVIRONMENT

=head2 SCRIPT_MODE => bool

If set to true, will try to complete word argument like C<tex> (i.e. word that
does not yet have any C<::> with list of scripts instead of module names). This
is useful for completing L<lcpanm-script>.
